org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mod_id=makebloodmagicgreatagain
mod_name=Make Blood Magic Great Again
mod_version=1.0.0
mod_group_id=com.mbmg.makebloodmagicgreatagain
mod_authors=MakeBloodMagicGreatAgain
mod_license=MIT
mod_description=血魔法附属mod：束灵头盔可装备植物魔法意志、束灵套可用新生魔艺改衣台装纤维（T0=Ⅰ, T1=Ⅱ×2, T2=Ⅲ×3, T3=Ⅲ×3）+ 附魔装置逐级升级、束灵胸甲+无尽催化剂升级点数上限至Integer.MAX_VALUE。

systemProp.java.net.preferIPv4Stack=true
