modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="bloodmagic"
    mandatory=true
    versionRange="[3.3.8-50,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="botania"
    mandatory=false
    versionRange="[1.20.1-441,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="ars_nouveau"
    mandatory=false
    versionRange="[4.12.7,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="avaritia"
    mandatory=false
    versionRange="[1.4.1,)"
    ordering="AFTER"
    side="BOTH"
